### ISSUE TITLE
有一处的样式有问题

### ISSUE THREAD

**Issue by zgcwkj** [liboysoft/typecho-lingonberry#1]
下面的页码显示有问题，可以通过该样式（style.css）文件达到和别打一致的效果

**Comment by liboysoft** [comment]
@zgcwkj 看到你的评论，未能及时回复。啧啧，typecho相关已经存档，我很想来修复一下，有过有更新就有修复

**Comment by zgcwkj** [comment]
这是我朋友的，修复方法》http://yoouu.cn/app/blog/usr/themes/lingonberry/style.css
